/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#111224',
        'surface-dim': '#111224',
        'surface-bright': '#37374c',
        'surface-container-lowest': '#0b0c1e',
        'surface-container-low': '#191a2c',
        'surface-container': '#1d1e31',
        'surface-container-high': '#27283c',
        'surface-container-highest': '#323347',
        'surface-variant': '#323347',
        'on-surface': '#e1e0fa',
        'on-surface-variant': '#bbcac7',
        'inverse-surface': '#e1e0fa',
        'inverse-on-surface': '#2e2f42',
        outline: '#859491',
        'outline-variant': '#3c4947',
        'surface-tint': '#47dbcf',
        primary: '#47dbcf',
        'on-primary': '#003733',
        'primary-container': '#0dbeb2',
        'on-primary-container': '#004742',
        'inverse-primary': '#006a63',
        'primary-fixed': '#6af8eb',
        'primary-fixed-dim': '#47dbcf',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#00504a',
        secondary: '#ffca45',
        'on-secondary': '#3f2e00',
        'secondary-container': '#e4ae00',
        'on-secondary-container': '#5b4400',
        'secondary-fixed': '#ffdf9a',
        'secondary-fixed-dim': '#f7be1d',
        'on-secondary-fixed': '#251a00',
        'on-secondary-fixed-variant': '#5a4300',
        tertiary: '#d2bbff',
        'on-tertiary': '#3f008e',
        'tertiary-container': '#ba98ff',
        'on-tertiary-container': '#5000b1',
        'tertiary-fixed': '#eaddff',
        'tertiary-fixed-dim': '#d2bbff',
        'on-tertiary-fixed': '#25005a',
        'on-tertiary-fixed-variant': '#5a00c6',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#111224',
        'on-background': '#e1e0fa',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'gutter-sm': '1rem',
        'gutter-lg': '2rem',
        margin: '2rem',
        'margin-sm': '1rem',
        'margin-lg': '3rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', fontWeight: '800', letterSpacing: '-0.03em' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-xl': ['40px', { lineHeight: '48px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.015em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.01em' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.02em' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500', letterSpacing: '0.04em' }],
      },
      boxShadow: {
        low: '0 4px 16px -2px rgba(11,12,30,0.8), 0 0 0 1px rgba(234,179,8,0.08)',
        high: '0 16px 36px -4px rgba(7,8,20,0.9), 0 0 24px rgba(13,190,178,0.12), 0 0 0 1px rgba(234,179,8,0.2)',
        'glow-primary': '0 0 18px rgba(13,190,178,0.45)',
        'glow-primary-lg': '0 0 28px rgba(71,219,207,0.55)',
        'glow-gold': '0 0 18px rgba(255,202,69,0.35)',
        'glow-violet': '0 0 18px rgba(186,152,255,0.35)',
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
      animation: {
        shimmer: 'shimmer 1.8s infinite',
        float: 'float 4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
